# Generated by Django 5.1.2 on 2024-10-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_category_store_remove_product_vendor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="item_number",
            field=models.IntegerField(default=0),
        ),
    ]
