# Generated by Django 5.1.2 on 2024-10-28 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_vendor_remove_product_vendor_name_product_profit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="product",
            name="profit",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sales",
        ),
        migrations.RemoveField(
            model_name="product",
            name="store",
        ),
        migrations.RemoveField(
            model_name="store",
            name="location",
        ),
        migrations.AddField(
            model_name="product",
            name="vendor_name",
            field=models.CharField(default="Unknown Vendor", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sales.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="store",
            name="zip_code",
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name="Vendor",
        ),
    ]
