# Generated by Django 5.1.2 on 2024-10-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_vendor_remove_product_vendor_name_product_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_name",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="store",
            name="store_location",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
