# Generated by Django 5.1.2 on 2024-10-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_remove_product_name_remove_product_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="product",
        ),
        migrations.AddField(
            model_name="sale",
            name="item_name",
            field=models.CharField(default="Unknown Item", max_length=255),
        ),
        migrations.AddField(
            model_name="sale",
            name="profit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="sale",
            name="sale_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="sale",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
