# Generated by Django 5.1.2 on 2024-10-28 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_remove_sale_product_sale_item_name_sale_profit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.product",
            ),
        ),
    ]
