# Generated by Django 5.1.2 on 2024-10-28 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0011_sale_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.product",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="item_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="sale",
            name="profit",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="sale",
            name="sale_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
